parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string

jobs:
- deployment: deploy_synapse_sql_serverless
  displayName: 'Deploy to synapse sql serverless'
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          displayName: 'Listing SQL Scripts'
          inputs:
            targetType: 'inline'
            script: Write-Host "##vso[task.setvariable variable=sqlfiles]$(Get-ChildItem -PATH '$(Pipeline.Workspace)/ciartifacts/serverless_sql_scripts/*.sql')"
                    Write-Host $sqlfiles
        
        - bash: |
            echo "##vso[task.setvariable variable=sqlfiles2]$(ls '$(Pipeline.Workspace)/ciartifacts/serverless_sql_scripts/' )" 
          displayName: "Set new variable value"

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops

        - task: SqlAzureDacpacDeployment@1
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            AuthenticationType: 'server'
            ServerName: $(synapseSqlPoolServer)-ondemand.database.windows.net
            DatabaseName: $(synapseSqlServerlessDBName)
            SqlUsername: '$(synapseSqlPoolAdminUsername)'
            SqlPassword: '$(synapseSqlPoolAdminPassword)'
            deployType: 'sqlTask'
            SqlFile: '$(Pipeline.Workspace)/ciartifacts/serverless_sql_scripts/deploy_sql.sql'
            SqlAdditionalArguments: '-Variable ADLSLocation=abfss://datalake@$(datalakeAccountName).dfs.core.windows.net/data/interim/'
          displayName: 'Azure Synapse SQL Serverless'